#Jumpbox Setup
Vagrant.configure("2") do |config|
  config.vm.define "jumpbox" do |jumpbox|
    jumpbox.vm.box = "ubuntu/xenial64"
    jumpbox.vm.hostname = 'jumpbox'
    jumpbox.vm.box_url = "ubuntu/xenial64"
    jumpbox.vm.provision :shell, path: "bootstrap_jumpbox.sh"

    jumpbox.vm.network :private_network, ip: "192.168.99.100"

    jumpbox.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "jumpbox"]
    end
  end

#Artifactory Setup
  config.vm.define "artifactory" do |artifactory|
    artifactory.vm.box = "ubuntu/xenial64"
    artifactory.vm.hostname = 'apache'
    artifactory.vm.box_url = "ubuntu/xenial64"
    artifactory.vm.provision :shell, path: "bootstrap_artifactory.sh"

    artifactory.vm.network :private_network, ip: "192.168.99.101"

    artifactory.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--name", "artifactory"]
    end
  end

#Concourse CI Setup
  config.vm.define "concourse" do |concourse|
    concourse.vm.box = "ubuntu/xenial64"
    concourse.vm.hostname = 'concourse'
    concourse.vm.box_url = "ubuntu/xenial64"
    concourse.vm.provision :shell, path: "bootstrap_concourse.sh"

    concourse.vm.network :private_network, ip: "192.168.99.102"

    concourse.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 4096]
      v.customize ["modifyvm", :id, "--name", "concourse"]
    end
  end

end
